package FormuláriosRally;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import Classes.GrupoSessao;
import model.dao.GrupoDAO;
import model.dao.PostoDeControleDAO;
import model.dao.GabaritoDAO;
import model.dao.AgrupamentoDAO;
import model.bean.Grupo;
import model.bean.Agrupamento;

public class FrmCodigoCheckIn extends javax.swing.JFrame {

    private GrupoSessao grupoObjeto;
    private GrupoDAO fcnGrupo;
    private PostoDeControleDAO fcnPostoDeControle;
    private GabaritoDAO fcnGabarito;
    private AgrupamentoDAO fcnAgrupamento;
    private Grupo grupo;
    private Agrupamento agrupamento;
    
    public FrmCodigoCheckIn() {
        initComponents();
        
        fcnGrupo = new GrupoDAO();
        fcnPostoDeControle = new PostoDeControleDAO();
        fcnGabarito = new GabaritoDAO();
        fcnAgrupamento = new AgrupamentoDAO();
    }
    
    @Override
    public void dispose(){
        if(fcnAgrupamento.conexao != null)
            try {
                fcnAgrupamento.closeConexao();
            } catch (SQLException e) {
            }
        if(fcnGrupo.conexao != null)
            try {
                fcnGrupo.closeConexao();
            } catch (SQLException e) {
            }
        if(fcnGabarito.conexao != null)
            try {
                fcnGabarito.closeConexao();
            } catch (SQLException e) {
            }
        if(fcnPostoDeControle.conexao != null)
            try {
                fcnPostoDeControle.closeConexao();
            } catch (SQLException e) {
            }
        super.dispose();
    }
    
    private void preenchimentoObjeto(){
        //Preenche as informações num objeto que será usado no programa todo
        grupoObjeto = new GrupoSessao();
        
        grupoObjeto.setCodigoAgrupamento(grupo.getCodigoAgrupamento());
        grupoObjeto.setCodigoGabaritoFase1(fcnGabarito.novoVazio());
        grupoObjeto.setCodigoGabaritoFase2(fcnGabarito.novoVazio());
        grupoObjeto.setCodigoGrupo(grupo.getCodigoGrupo());
        grupoObjeto.setCodigoPostoInicial(grupo.getCodigoPostoInicial());
        grupoObjeto.setNome(grupo.getNome());
        grupoObjeto.setNomePosto(fcnPostoDeControle.find(grupo.getCodigoPostoInicial()).getNomePC());
        grupoObjeto.setPontuacao(0);
        grupoObjeto.setPostoAtual(grupo.getCodigoPostoInicial());
        if(Integer.parseInt(edtCheckIn.getText().substring(7,8)) == 1)
            grupoObjeto.setLiderSegundaFase(true);
        else
            grupoObjeto.setLiderSegundaFase(false);
        //Atualiza os gabaritos
        grupo.setCodigoGabaritoFase1(grupoObjeto.getCodigoGabaritoFase1());
        fcnGrupo.update(grupo);
        agrupamento = fcnAgrupamento.find(grupo.getCodigoAgrupamento());
        agrupamento.setCodigoGabaritoFase2(grupoObjeto.getCodigoGabaritoFase2());
        fcnAgrupamento.updateAgrup(agrupamento);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFundo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        edtCheckIn = new javax.swing.JTextField();
        btnCheckIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlFundo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFundo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("<html><center>Insira o Código de Check In </center></html>");

        edtCheckIn.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        edtCheckIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        edtCheckIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edtCheckInKeyTyped(evt);
            }
        });

        btnCheckIn.setBackground(new java.awt.Color(255, 51, 51));
        btnCheckIn.setFont(new java.awt.Font("sansserif", 1, 36)); // NOI18N
        btnCheckIn.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckIn.setText("Check In");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFundoLayout = new javax.swing.GroupLayout(pnlFundo);
        pnlFundo.setLayout(pnlFundoLayout);
        pnlFundoLayout.setHorizontalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edtCheckIn, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFundoLayout.createSequentialGroup()
                        .addGap(0, 13, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        pnlFundoLayout.setVerticalGroup(
            pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFundoLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(edtCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed
        if (edtCheckIn.getText().length() == 8) {
            grupo = fcnGrupo.find(Integer.parseInt(edtCheckIn.getText().substring(0, 3)));
            if(grupo.getCodigoGrupo() == 0)
                JOptionPane.showMessageDialog(null, "Código de Check In não encontrado!"
                        + "\nContate o Funcionário mais próximo para maiores informações.", "Check In - Rally do Conhecimento", 2);
            else{
                preenchimentoObjeto();
                
                new FrmSenhaFase(grupoObjeto).setVisible(true);
                this.dispose();
            }
        } 
        else {
            JOptionPane.showMessageDialog(null, "Código de Check In incompleto!"
                    + "\nContate o Funcionário mais próximo para maiores informações.", "Check In - Rally do Conhecimento", 1);
        }


    }//GEN-LAST:event_btnCheckInActionPerformed

    private void edtCheckInKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edtCheckInKeyTyped
        if (edtCheckIn.getText().length() == 8)
            evt.consume();        
        if (!"0123456789".contains(String.valueOf(evt.getKeyChar())))
            evt.consume();
    }//GEN-LAST:event_edtCheckInKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCodigoCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCodigoCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCodigoCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCodigoCheckIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCodigoCheckIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JTextField edtCheckIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlFundo;
    // End of variables declaration//GEN-END:variables
}
